name: learn-github-actions
on: [push]
jobs:
  run-bats-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install bats bats-assert bats-support
      - run: node_modules/bats/bin/bats test/*.bats
