name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install --verbose bats bats-assert bats-support
      - run: which bats
      - run: pwd
      - run: bats test/*.bats
